export const SET_ACTIVE_TAB = "SET_ACTIVE_TAB";

// API USER
export const GET_USER_ALL = "GET_USER_ALL";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "UPDATE_USER";
export const GET_USER_LOGIN_INFO = "GET_USER_LOGIN_INFO";
export const GET_USERS_J0IN_IN_PROJECT = "GET_USERS_J0IN_IN_PROJECT";

// API PROJECT
export const GET_PROJECT_ALL = "GET_PROJECT_ALL";
export const GET_PROJECT_BY_USER = "GET_PROJECT_BY_USER";
export const GET_PROJECT_BY_ID = "GET_PROJECT_BY_ID";
export const SELECTED_PROJECT = "SELECTED_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

// API TASK
export const GET_TASK_ALL = "GET_TASK_ALL";
export const GET_TASK_BY_USER = "GET_TASK_BY_USER";
export const GET_TASK_BY_ID = "GET_TASK_BY_ID";
export const GET_TASK_BY_PROJECT_ID = "GET_TASK_BY_PROJECT_ID";
export const UPDATE_TASK_BY_PROJECT = "UPDATE_TASK_BY_PROJECT";
export const CREATE_TASK = "CREATE_TASK";
export const UPDATE_TASK = "UPDATE_TASK";
export const DELETE_TASK = "DELETE_TASK";

// THEME
export const SET_THEME = "SET_THEME";

// TASK STATUS
export const TO_DO_TASK_STATUS = "TO_DO_TASK_STATUS";
export const IN_PROGRESS_TASK_STATUS = "IN_PROGRESS_TASK_STATUS";
export const DONE_TASK_STATUS = "DONE_TASK_STATUS";
